site_name: munstergenes
site_url: https://monstergenes.github.io/mkdocs-theme.io/
site_description: my-theme-project
site_author: munstergenes

repo_url: https://github.com/monstergenes/mkdocs-theme.io/
edit_uri: root/custom_theme/docs/

Theme:
    name: munsterskreations
    locale: en
    highlights: true 
    hljs_languages:
        - yaml
        - django
    analytics: {}


    custom_theme:
          - main: main.html
          - Css: styles.css
    docs:
          - about: about.md
          - index: index.md

